name: Linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    name: Run ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Run Ruff
        run: ruff check ./backend

  isort:
    name: Run isort
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Isort
        run: |
          python -m pip install --upgrade pip
          pip install isort
      
      - name: Run Isort
        run: isort ./backend

  black:
    name: Run black
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      
      - name: Run Black
        run: black ./backend
