name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Run Isort
        if: always()
        run: |
          python -m pip install isort
          isort ./backend --check-only --diff

      - name: Run Black
        if: always()
        run: |
          python -m pip install black
          black ./backend --diff

      - name: Run Flake8
        if: always()
        run: |
          python -m pip install flake8
          flake8 ./backend

      - name: Run Ruff Linter
        if: always()
        run: |
          python -m pip install ruff
          ruff check ./backend

      - name: Run Ruff Formatter
        if: always()
        run: |
          python -m pip install ruff
          ruff format ./backend --check
