name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Isort
        continue-on-error: true
        run: |
          python -m pip install isort
          isort ./backend

      - name: Run Black
        continue-on-error: true
        run: |
          python -m pip install black
          black ./backend

      - name: Run Flake8
        continue-on-error: true
        run: |
          python -m pip install flake8
          flake8 ./backend

      - name: Run Ruff
        continue-on-error: true
        run: |
          python -m pip install ruff
          ruff check ./backend
