name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: ${{ vars.POSTGRES_IMAGE }}
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_TEST_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_TEST_DB }}
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install Dependecies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_TEST_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_TEST_DB }}
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
